import "./globals.css";
import "../node_modules/bootstrap/dist/css/bootstrap.css";
import { Inter, Poppins } from "next/font/google";
import { Providers } from "./redux/provider";

import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextTopLoader
          color="#000"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
